# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Initialize table CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './util/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./util/
      run: npm install
      
    - name: Run initialize js script
      working-directory: ./util/
      run: node initialize.js
      
    - name: Push to origin
      working-directory: ./profile/
      run: |
        git add README.md;
        git config user.name github-actions
        git config user.email github-actions@github.dom
        git commit -m "Docs: 문제 풀이 현황 테이블 정기 업데이트"
        git push origin main
